# Testplan properties
number.of.threads=1
ramp.up.seconds=10
duration.seconds=30
startup.delay.seconds=2

# Thinking time
sky.thinking.time=1000

# Sign up tests
number.of.new.user=2

test.name=
test.runId=R1

